<!-- block5 -->
<?php foreach ($this->articles as $article) : ?>
<div class="slide" id="slide5" data-slide="5" data-stellar-background-ratio="0.5" style="background-image: url(/image/1920/1440/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>); overflow: hidden; min-height:1000px; background-color:#efefe3; background-repeat:no-repeat;">
<div class="container clearfix">
	<div id="main" class="grid_7 bright">
		<div style="padding: 20px;">
			<h1><?php echo $article->pagetitle; ?></h1>
            <h2 style="line-height: 22px;"><?php echo strip_tags($article->intro, '<br><br />'); ?></h2>
            <?php echo $article->content; ?>
            <?php $images = unserialize($article->bild); ?>

		</div>
	</div>

	<div id="decorative" class="grid_5 omega">
   		<?php if (!empty($images)) : ?>
   		<div class="box" style=""> 
	   	<?php foreach ($images as $image) : ?>
    		<div style="padding: 10px 10px 10px 10px; background-color: #f3f3f3;"><img src="/image/350/300/1/<?php echo $article->idart; ?>/<?php echo $image; ?>" title="<?php echo $article->pagetitle; ?>"></div>
		<?php endforeach; ?>
		</div>
		<?php endif; ?>
    </div>
</div>
</div>
<?php endforeach; ?>
