<!--post nav-->
	<!-- <ul id="nav">
                <li id="blockLink1"><a href="#block1" class="block-link" title=""></a></li>
                <li id="blockLink2"><a href="#block2" class="block-link" title=""></a></li>
                <li id="blockLink3"><a href="#block3" class="block-link" title=""></a></li>
                <li id="blockLink4"><a href="#block4" class="block-link" title=""></a></li>
                <li id="blockLink5"><a href="#block5" class="block-link" title=""></a></li>
                <li id="blockLink6"><a href="#block6" class="block-link" title=""></a></li>
                <li id="blockLink7"><a href="#block7" class="block-link" title=""></a></li>
	</ul> -->
<!--end post nav -->
        
            
<script type="application/x-moraso" src="List.Articles:Home">
    categories = 13
    useOfStartArticle = 3
    template = block1
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
</script> 

<script type="application/x-moraso" src="List.Articles:Service">
    categories = 7
    useOfStartArticle = 3
    template = block2
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script>

<script type="application/x-moraso" src="List.Articles:Portfolio">
    categories = 8
    useOfStartArticle = 3
    template = block3
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script>

<script type="application/x-moraso" src="List.Articles:About">
    categories = 9
    useOfStartArticle = 3
    template = block4
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script> 

<script type="application/x-moraso" src="List.Articles:Free">
    categories = 10
    useOfStartArticle = 3
    template = block5
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script> 

<script type="application/x-moraso" src="List.Articles:Partners">
    categories = 11
    useOfStartArticle = 3
    template = block6
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script> 

<script type="application/x-moraso" src="List.Articles:Contact">
    categories = 12
    useOfStartArticle = 3
    template = block7
    populateWith.intro.index = Einleitung
    populateWith.content.index = Fliesstext
    populateWith.bild.index = Bild
    populateWith.bild.type = property
    populateWith.bild.index = ModuleConfig_bild:Image_Media
</script> 		

