<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale = 1.0, user-scalable = no">
	<script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | Tim Friday | Landscape design"
    </script>
	<link rel="stylesheet" href="/skin/css/grid.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/skin/css/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/skin/css/normalize.css" type="text/css" media="screen">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script type="text/javascript" src="/skin/js/js.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.stellar.min.js"></script>
	<script type="text/javascript" src="/skin/js/waypoints.min.js"></script>
	<script type="text/javascript" src="/skin/js/jquery.easing.1.3.js"></script>
</head>
<body>

<div class="menu">	
	<div class="container clearfix">

		<div id="logo" class="grid_3">
			<img src="/skin/images/friday-logo.png" border="0" />
		</div>
		
		<div id="nav" class="grid_9 omega">
			<ul class="navigation">
				<script type="application/x-moraso" src="Navigation:main"></script>
				<script type="application/x-moraso" src="Language.Selector:sprache"></script>
			</ul>
		</div>
	
	</div>
</div>

<script type="application/x-moraso" src="Template:Main">
	defaultTemplate = default
                    
    template.default.name = Standard
	template.default.file = templates/main/default.phtml 
    
	template.start.name = Start
	template.start.file = templates/main/start.phtml 
</script>






</body>
</html>
